services:
  media-cluster-scheduler:
    image: scheduler
    container_name: media-cluster-scheduler
    restart: unless-stopped
    user: "9001:9001"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    read_only: true
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 512M
    environment:
      TZ: "America/Los_Angeles"
      XMX: 256M
      # Only used on the first run
      #application.firstrun.username: ${some-env-var-or-clear-text-value}
      #application.firstrun.password: ${some-env-var-or-clear-text-value}
    ports:
      - "8080:8080/tcp"
    network_mode: bridge
    volumes:
      # Application settings and logs
      - "./scheduler/home/user/app-data:/home/user/app-data"
      # Media files to process (needs access to all cluster's files)
      - "./scheduler/media:/home/user/media"
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 8m
